import SCREENS from '@src/SCREENS';

const EXPERTISE_TO_RHP: Record<typeof SCREENS.EXPERTISE_FULLSCREEN_PAGE, string[]> = {
    [SCREENS.EXPERTISE_FULLSCREEN_PAGE]: [
        SCREENS.EXPERTISE_NAV.FIRST,
        SCREENS.EXPERTISE_NAV.SECOND,
        SCREENS.EXPERTISE_NAV.THIRD,
        SCREENS.EXPERTISE_PARAM_NAV.PARAM,
        SCREENS.EXPERTISE_PARAM_NAV.LAST,
    ],
};

export default EXPERTISE_TO_RHP;
