name: 'Validate Regression Test Output'
description: 'Validates the output of regression tests and determines if a test action should fail.'
inputs:
  COUNT_DEVIATION:
    description: Allowable deviation for the mean count in regression test results.
    required: true
runs:
  using: 'node24'
  main: './index.js'
