import {NativeModules} from 'react-native';
import Onyx from 'react-native-onyx';
import type {ValueOf} from 'type-fest';
import CONST from '@src/CONST';
import ONYXKEYS from '@src/ONYXKEYS';
import type {HybridApp} from '@src/types/onyx';
import type HybridAppSettings from './types';

function parseHybridAppSettings(hybridAppSettings: string): HybridAppSettings {
    return JSON.parse(hybridAppSettings) as HybridAppSettings;
}

function setReadyToShowAuthScreens(readyToShowAuthScreens: boolean) {
    Onyx.merge(ONYXKEYS.HYBRID_APP, {readyToShowAuthScreens});
}

function setNewDotSignInState(newDotSignInState: ValueOf<typeof CONST.HYBRID_APP_SIGN_IN_STATE>) {
    Onyx.merge(ONYXKEYS.HYBRID_APP, {newDotSignInState});
}

function setOldDotSignInState(oldDotSignInState: ValueOf<typeof CONST.HYBRID_APP_SIGN_IN_STATE>) {
    Onyx.merge(ONYXKEYS.HYBRID_APP, {oldDotSignInState});
}

/*
 * Starts HybridApp sign-in flow from the beginning. Optionally, it can clear session onyx value
 */
function resetSignInFlow(clearSession = false) {
    const maybeClearSession = () => {
        if (!clearSession) {
            return Promise.resolve();
        }

        return Onyx.merge(ONYXKEYS.SESSION, null);
    };

    maybeClearSession().then(() =>
        Onyx.merge(ONYXKEYS.HYBRID_APP, {
            readyToShowAuthScreens: false,
            oldDotSignInError: null,
            oldDotSignInState: CONST.HYBRID_APP_SIGN_IN_STATE.NOT_STARTED,
            newDotSignInState: CONST.HYBRID_APP_SIGN_IN_STATE.NOT_STARTED,
        }),
    );
}

/*
 * Starts HybridApp sign-in flow, but also deletes authToken
 */
function resetSignInFlowBeforeValidateAndSubmit() {
    Onyx.merge(ONYXKEYS.SESSION, {
        authToken: null,
    }).then(() => {
        resetSignInFlow();
    });
}

/*
 * Sets proper sign-in state after sign-out on NewDot side
 */
function resetStateAfterSignOut() {
    Onyx.merge(ONYXKEYS.HYBRID_APP, {
        useNewDotSignInPage: true,
        readyToShowAuthScreens: false,
        oldDotSignInError: null,
        oldDotSignInState: CONST.HYBRID_APP_SIGN_IN_STATE.NOT_STARTED,
        newDotSignInState: CONST.HYBRID_APP_SIGN_IN_STATE.NOT_STARTED,
    });
}

function startOldDotSignIn(autoGeneratedLogin: string, autoGeneratedPassword: string) {
    Onyx.merge(ONYXKEYS.HYBRID_APP, {
        oldDotSignInState: CONST.HYBRID_APP_SIGN_IN_STATE.STARTED,
    });

    NativeModules.HybridAppModule.signInToOldDot(autoGeneratedLogin, autoGeneratedPassword);
}

function retryOldDotSignInAfterFailure(autoGeneratedLogin: string, autoGeneratedPassword: string) {
    Onyx.merge(ONYXKEYS.HYBRID_APP, {
        oldDotSignInError: null,
        oldDotSignInState: CONST.HYBRID_APP_SIGN_IN_STATE.RETRYING_AFTER_FAILURE,
    });

    NativeModules.HybridAppModule.signInToOldDot(autoGeneratedLogin, autoGeneratedPassword);
}

function finishOldDotSignIn(errorMessage: string | null) {
    Onyx.merge(ONYXKEYS.HYBRID_APP, {
        oldDotSignInError: errorMessage,
        oldDotSignInState: CONST.HYBRID_APP_SIGN_IN_STATE.FINISHED,
    });
}

function prepareHybridAppAfterTransitionToNewDot(hybridApp: HybridApp) {
    if (hybridApp?.useNewDotSignInPage) {
        return Onyx.merge(ONYXKEYS.HYBRID_APP, {
            ...hybridApp,
            readyToShowAuthScreens: false,
            oldDotSignInError: null,
            oldDotSignInState: CONST.HYBRID_APP_SIGN_IN_STATE.NOT_STARTED,
            newDotSignInState: CONST.HYBRID_APP_SIGN_IN_STATE.NOT_STARTED,
        });
    }

    // When we transition with useNewDotSignInPage === false, it means that we're already authenticated on NewDot side.
    return Onyx.merge(ONYXKEYS.HYBRID_APP, {
        ...hybridApp,
        readyToShowAuthScreens: true,
    });
}

function waitForSignOut() {
    Onyx.merge(ONYXKEYS.HYBRID_APP, {
        oldDotSignInState: CONST.HYBRID_APP_SIGN_IN_STATE.WAITING_FOR_SIGN_OUT,
        newDotSignInState: CONST.HYBRID_APP_SIGN_IN_STATE.WAITING_FOR_SIGN_OUT,
    });
}

export {
    parseHybridAppSettings,
    setReadyToShowAuthScreens,
    setNewDotSignInState,
    setOldDotSignInState,
    resetSignInFlow,
    retryOldDotSignInAfterFailure,
    finishOldDotSignIn,
    startOldDotSignIn,
    prepareHybridAppAfterTransitionToNewDot,
    waitForSignOut,
    resetSignInFlowBeforeValidateAndSubmit,
    resetStateAfterSignOut,
};
