export default {
    Avatar1: '../../../assets/images/avatars/user/default-avatar_1.svg',
    Avatar2: '../../../assets/images/avatars/user/default-avatar_2.svg',
    Avatar3: '../../../assets/images/avatars/user/default-avatar_3.svg',
    Avatar4: '../../../assets/images/avatars/user/default-avatar_4.svg',
    Avatar5: '../../../assets/images/avatars/user/default-avatar_5.svg',
    Avatar6: '../../../assets/images/avatars/user/default-avatar_6.svg',
    Avatar7: '../../../assets/images/avatars/user/default-avatar_7.svg',
    Avatar8: '../../../assets/images/avatars/user/default-avatar_8.svg',
    Avatar9: '../../../assets/images/avatars/user/default-avatar_9.svg',
    Avatar10: '../../../assets/images/avatars/user/default-avatar_10.svg',
    Avatar11: '../../../assets/images/avatars/user/default-avatar_11.svg',
    Avatar12: '../../../assets/images/avatars/user/default-avatar_12.svg',
    Avatar13: '../../../assets/images/avatars/user/default-avatar_13.svg',
    Avatar14: '../../../assets/images/avatars/user/default-avatar_14.svg',
    Avatar15: '../../../assets/images/avatars/user/default-avatar_15.svg',
    Avatar16: '../../../assets/images/avatars/user/default-avatar_16.svg',
    Avatar17: '../../../assets/images/avatars/user/default-avatar_17.svg',
    Avatar18: '../../../assets/images/avatars/user/default-avatar_18.svg',
    Avatar19: '../../../assets/images/avatars/user/default-avatar_19.svg',
    Avatar20: '../../../assets/images/avatars/user/default-avatar_20.svg',
    Avatar21: '../../../assets/images/avatars/user/default-avatar_21.svg',
    Avatar22: '../../../assets/images/avatars/user/default-avatar_22.svg',
    Avatar23: '../../../assets/images/avatars/user/default-avatar_23.svg',
    Avatar24: '../../../assets/images/avatars/user/default-avatar_24.svg',
};
