import SCREENS from '@src/SCREENS';
import {FullScreenName} from './types';

const FULL_SCREEN_TO_RHP_MAPPING: Partial<Record<FullScreenName, string[]>> = {
    [SCREENS.SETTINGS.PROFILE.ROOT]: [SCREENS.SETTINGS.PROFILE.DISPLAY_NAME, SCREENS.SETTINGS.PROFILE.CONTACT_METHODS],
    [SCREENS.SETTINGS.PREFERENCES.ROOT]: [SCREENS.SETTINGS.PREFERENCES.PRIORITY_MODE],
};

export default FULL_SCREEN_TO_RHP_MAPPING;
